"""The meetings folder's own `INDEX.md` — one row per meeting, and the dashboard.

**A different file from this repository's `INDEX.md`.** That one is a hand-kept
map of the source tree; this one is generated, regenerated at the end of every
transcription and by `referat index`, and never hand-edited. The meetings
`CLAUDE.md` says so in the folder itself, because an edit to it survives exactly
until the next meeting finishes.

It works as a dashboard only because the scaffold's `.vscode/settings.json`
associates `*.md` with the Markdown preview editor in that workspace, so opening
the folder in VS Code shows a rendered table of links rather than pipes and
dashes. Until the extension arrives at build step 11, this file is the whole
browsing layer.

Light on purpose: JSON, paths and string formatting. It is imported by
:mod:`referat.cli` at module scope and called from the transcription pipeline, so
it may not pull in any part of the `transcribe` extra.
"""

from __future__ import annotations

import datetime as dt
import logging
from pathlib import Path

from referat import paths, voices
from referat.config import Config
from referat.meeting import Meeting, format_duration

log = logging.getLogger(__name__)

HEADER = f"""<!-- Generated by `referat index`, and again at the end of every
     transcription. Hand edits are lost on the next run: change a meeting's
     `{paths.NOTES_MD}` title, not this table. -->

# Meetings
"""


def meeting_title(meeting: Meeting) -> str:
    """The meeting's title: the H1 of its `notes.md`, or its id when it has none.

    Deliberately *not* a `meta.json` key. The title is a product of the `/cleanup`
    pass, and the meetings folder's `CLAUDE.md` declares `meta.json` off limits to
    it — so the title lives on the notes side of that line and the raw record
    stays raw. Build step 13's digest blocks open with the same title and share
    this function rather than growing a second reader of the same file.

    Only the first heading counts, and only when it is the first non-blank line:
    a `#` further down is a mistake in the notes rather than a second title, and
    picking one up would put a section heading in the dashboard.
    """
    try:
        text = (meeting.dir / paths.NOTES_MD).read_text(encoding="utf-8")
    except OSError:
        return meeting.id
    for line in text.splitlines():
        if not line.strip():
            continue
        if line.startswith("# "):
            return line[2:].strip() or meeting.id
        return meeting.id
    return meeting.id


def status_words(meeting: Meeting) -> str:
    """The lifecycle value as words: `notes_written` reads `notes written` here.

    Underscores are right in `meta.json` and in `referat list`, whose columns are
    separated by spaces and where a two-word cell would read as two columns. They
    are wrong in a rendered Markdown table somebody is looking at, which is what
    this file becomes with the scaffold's Markdown-preview association.

    Deliberately a formatting rule and not a map of value to sentence. A map would
    be a second vocabulary alongside :class:`referat.meeting.MeetingStatus`, and
    the first new state nobody added a row for would render as a blank.
    """
    return str(meeting.status).replace("_", " ")


def _link(meeting: Meeting, filename: str) -> str:
    """A relative Markdown link to a file in the meeting folder, or `-` if absent.

    Relative, and relative to the meetings folder: this file is written into a
    folder that is synced, so an absolute path into this machine would be wrong
    everywhere it was read from.
    """
    if not (meeting.dir / filename).exists():
        return "-"
    return f"[{filename}]({meeting.id}/{filename})"


def _row(meeting: Meeting) -> tuple[str, ...]:
    """One table row: when, what, how long, how it went, and what is still open."""
    unnamed = len(voices.unknown_speakers(meeting))
    return (
        meeting.started_at.strftime("%Y-%m-%d %H:%M"),
        meeting_title(meeting),
        format_duration(meeting.duration_seconds),
        status_words(meeting),
        str(unnamed) if unnamed else "-",
        _link(meeting, paths.TRANSCRIPT_MD),
        _link(meeting, paths.NOTES_MD),
    )


COLUMNS = ("Date", "Title", "Duration", "Status", "Unnamed", "Transcript", "Notes")


def render_index(meetings: list[Meeting], staged: int = 0) -> str:
    """The whole file, as Markdown.

    Newest first, unlike `referat list`. The list is read at a prompt with the
    last line closest to the cursor; this one is read from the top.

    `staged` is the count of meetings that are still in the staging folder because
    they kept their audio. They get a **footer line rather than rows**: they are
    not in this folder, so there is nothing here to link to, and naming them with
    absolute paths would put this machine's layout into a synced file. The line
    mirrors what `referat list` already prints, so the two do not disagree about
    what is waiting.
    """
    lines = [HEADER]
    if not meetings:
        lines.append("No meetings yet.\n")
    else:
        rows = [_row(m) for m in reversed(meetings)]
        lines.append("| " + " | ".join(COLUMNS) + " |")
        lines.append("| " + " | ".join("---" for _ in COLUMNS) + " |")
        lines += ["| " + " | ".join(row) + " |" for row in rows]
        lines.append("")

        total = len(meetings)
        summary = f"{total} meeting{'s' if total != 1 else ''}."
        pending = sum(1 for row in rows if row[4] != "-")
        if pending:
            summary += (
                f" {pending} with speakers nobody has named yet — run `referat label`."
            )
        lines.append(summary)

    if staged:
        lines.append("")
        lines.append(
            f"{staged} further meeting{'s are' if staged != 1 else ' is'} still local "
            f"with the audio kept, because the transcript did not come out clean — "
            f"not listed above, and not in this folder. Run `referat rerun <id>`; "
            f"`referat list` shows them."
        )

    lines.append("")
    lines.append(
        f"<sub>Generated {dt.datetime.now().strftime('%Y-%m-%d %H:%M')} "
        f"by `referat index`.</sub>"
    )
    return "\n".join(lines) + "\n"


def write_index(config: Config) -> Path | None:
    """Regenerate `<meetings_dir>/INDEX.md`. Returns the path, or None on failure.

    **Never raises.** It is called at the end of the transcription pipeline, and
    the rule that governs diarization governs this too: a dashboard that could not
    be written must cost the dashboard and nothing else. A meeting with a good
    transcript in it is not a failed meeting because a table did not render.
    """
    try:
        meetings_dir = config.paths.meetings_dir
        found = [Meeting.load(d) for d in paths.list_meeting_dirs(meetings_dir)]
        meetings = [m for m in found if m is not None]
        # Every root except the meetings folder itself is staging, and a meeting is
        # only there while it still has its audio.
        staged = sum(
            len(paths.list_meeting_dirs(root))
            for root in config.meeting_roots()
            if root != meetings_dir
        )
        target = meetings_dir / paths.INDEX_MD
        paths.write_text_atomic(target, render_index(meetings, staged))
    except Exception:
        log.warning("could not write the meetings INDEX.md", exc_info=True)
        return None
    log.debug("wrote %s (%d meetings)", target, len(meetings))
    return target


def run(config: Config) -> int:
    """`referat index`. Regenerate the dashboard on demand — after a `/cleanup` run,
    which is what gives a meeting its title."""
    target = write_index(config)
    if target is None:
        print(f"referat index: could not write {config.paths.meetings_dir / paths.INDEX_MD}")
        return 1
    count = len(paths.list_meeting_dirs(config.paths.meetings_dir))
    print(f"Wrote {target} ({count} meeting{'s' if count != 1 else ''}).")
    return 0
