"""Filesystem locations Referat uses, and helpers for meeting folders.

Nothing here reads the config file; callers pass in the meetings directory they
got from :mod:`referat.config`. That keeps this module import-safe and free of
circular imports.
"""

from __future__ import annotations

import datetime as dt
import json
import os
import shutil
import tempfile
from collections.abc import Sequence
from pathlib import Path

# --- Repository and packaged files -----------------------------------------

PACKAGE_DIR = Path(__file__).resolve().parent
"""The installed `referat/` package directory."""

REPO_ROOT = PACKAGE_DIR.parent
"""Repository root. Valid because Referat is installed editable on this machine."""

EXAMPLE_CONFIG_PATH = REPO_ROOT / "config.example.toml"
"""Template copied to `config.toml` on first run."""

MEETINGS_TEMPLATE_DIR = REPO_ROOT / "templates" / "meetings"
"""The scaffold copied into the meetings folder on first run: its `CLAUDE.md`, the
`/cleanup` slash command, the rule denying the `/cleanup` pass access to
`.voices/`, and the workspace setting that opens Markdown rendered.

Seeded file by file through :func:`seed_tree` and **never overwritten** — the
point of keeping the `/cleanup` prompt in a file is refining it in place.
"""

CONFIG_ENV_VAR = "REFERAT_CONFIG"


def config_path() -> Path:
    """Path to the active config file: `$REFERAT_CONFIG`, else repo-root config.toml."""
    override = os.environ.get(CONFIG_ENV_VAR)
    if override:
        return Path(override).expanduser().resolve()
    return REPO_ROOT / "config.toml"


# --- Per-user state ---------------------------------------------------------


def state_dir() -> Path:
    """`%LOCALAPPDATA%\\Referat` — logs and the tray status file live here."""
    local = os.environ.get("LOCALAPPDATA")
    base = Path(local) if local else Path.home() / "AppData" / "Local"
    return base / "Referat"


def default_staging_dir() -> Path:
    r"""`%LOCALAPPDATA%\Referat\recording` — where a meeting is recorded and
    transcribed before it is moved into the meetings folder.

    Recording never writes into the meetings folder, because that folder may be
    synced: see :meth:`referat.config.Config.staging_dir`.
    """
    return state_dir() / "recording"


def status_path() -> Path:
    """Status file the tray app writes and `referat status` reads."""
    return state_dir() / "status.json"


def log_path() -> Path:
    """Rotating log file for the tray app and CLI."""
    return state_dir() / "referat.log"


# --- Meeting folders --------------------------------------------------------

MEETING_ID_FORMAT = "%Y-%m-%d_%H%M"

MIC_WAV = "mic.wav"
SYSTEM_WAV = "system.wav"
TRANSCRIPT_MD = "transcript.md"
META_JSON = "meta.json"

NOTES_MD = "notes.md"
"""Written by the `/cleanup` pass, never by Referat itself. Its H1 is the meeting's
title everywhere a title is shown — see :func:`referat.index.meeting_title`."""

INDEX_MD = "INDEX.md"
"""The meetings folder's own dashboard, regenerated by :mod:`referat.index`.

A different file from the repository's `INDEX.md`: this one is generated and never
hand-edited."""

SPEAKERS_DIR = "speakers"
"""Per-meeting folder of WAV snippets, a few per speaker `referat label` has yet
to name. Cut during the transcription pipeline, because the WAVs it cuts them
from are deleted as soon as the meeting transcribes cleanly; deleted themselves
once their speaker has a name."""

VOICES_DIR = ".voices"
VOICES_JSON = "voices.json"
DO_NOT_SYNC_MD = "DO-NOT-SYNC.md"
"""The known-voices database, one per meetings folder rather than one per meeting.

It is biometric personal data about people who never asked to be in it: it never
leaves the machine, it is excluded from sync and from backups — which is what the
`DO-NOT-SYNC.md` beside it is for — and `referat label --forget <name>` deletes a
person outright.
"""


def meeting_id(started_at: dt.datetime) -> str:
    """Meeting id for a start time, e.g. `2026-08-27_1400`."""
    return started_at.strftime(MEETING_ID_FORMAT)


def parse_meeting_id(mid: str) -> dt.datetime:
    """Inverse of :func:`meeting_id`; ignores any `_2`-style collision suffix."""
    base = mid[: len(dt.datetime.now().strftime(MEETING_ID_FORMAT))]
    return dt.datetime.strptime(base, MEETING_ID_FORMAT)


def new_meeting_dir(
    parent: Path, started_at: dt.datetime, avoid: Sequence[Path] = ()
) -> Path:
    """Create and return a fresh meeting folder, suffixing `_2`, `_3`, ... on collision.

    The id has to be free in every root in `avoid` as well as in `parent`. A
    meeting is created in the staging folder and moved into the meetings folder
    once its audio is gone, so an id that is free in staging but taken in the
    destination would have to be renamed *after* it had been written into
    `meta.json`, used in `referat label <id>` and, at step 13, written into a
    digest doc as an anchor. Deciding it once, at creation, keeps the id stable
    for the life of the meeting.
    """
    base = meeting_id(started_at)
    roots = [parent, *avoid]
    name, n = base, 2
    while any((root / name).exists() for root in roots):
        name, n = f"{base}_{n}", n + 1
    folder = parent / name
    folder.mkdir(parents=True)
    return folder


def find_meeting_dir(roots: Sequence[Path], mid: str) -> Path | None:
    """Look up an existing meeting folder by id, across every root it may be in.

    A meeting lives in the staging folder while it still has audio and in the
    meetings folder once it does not, so anything that resolves an id by hand has
    to look in both — pass :meth:`referat.config.Config.meeting_roots`.
    """
    for root in roots:
        candidate = root / mid
        if candidate.is_dir():
            return candidate
    return None


def move_meeting_dir(folder: Path, destination_parent: Path) -> Path:
    """Move a finished meeting folder into `destination_parent`, returning the new path.

    Same volume in the normal case, so this is a rename and therefore atomic: the
    folder is either wholly in staging or wholly in the meetings folder, never
    half-copied into a folder something else is watching. Collisions are suffixed
    the way :func:`new_meeting_dir` suffixes them.
    """
    destination_parent.mkdir(parents=True, exist_ok=True)
    target = destination_parent / folder.name
    n = 2
    while target.exists():
        target = destination_parent / f"{folder.name}_{n}"
        n += 1
    return Path(shutil.move(str(folder), str(target)))


def voices_dir(meetings_dir: Path, override: Path | None = None) -> Path:
    """`<meetings_dir>/.voices`, or `override` when `[paths].voices_dir` names one.

    The override is what lets the meetings folder sit in Dropbox while the
    voiceprints do not — see :attr:`referat.config.PathsConfig.voices_dir`.
    Resolve it through :meth:`referat.config.Config.voices_dir` rather than
    calling this with two arguments at every site.
    """
    return override.expanduser() if override is not None else meetings_dir / VOICES_DIR


def list_meeting_dirs(meetings_dir: Path) -> list[Path]:
    """All meeting folders, oldest first. A folder counts if it has a meta.json."""
    if not meetings_dir.is_dir():
        return []
    dirs = [
        p
        for p in meetings_dir.iterdir()
        if p.is_dir() and p.name != VOICES_DIR and (p / META_JSON).exists()
    ]
    return sorted(dirs, key=lambda p: p.name)


# --- Seeding the meetings folder scaffold -----------------------------------


def seed_tree(template_root: Path, destination: Path) -> list[Path]:
    """Copy a template directory into `destination`, **never overwriting**.

    File by file: anything missing is copied, anything already there is left
    exactly as it is. Returns the files that were created, for the caller to log.

    Not overwriting is the whole contract. The `/cleanup` prompt lives in
    `.claude/commands/cleanup.md` precisely so it can be refined by editing
    Markdown, and a refinement clobbered on the next start would be worse than no
    scaffold at all. Repo template and live copy are therefore allowed to drift,
    and are reconciled by hand when a change is worth keeping.

    Empty directories in the template are not reproduced; there is no use for one,
    and a stray empty folder in the meetings tree would read as a broken meeting.
    """
    if not template_root.is_dir():
        return []
    created: list[Path] = []
    for source in sorted(template_root.rglob("*")):
        if not source.is_file():
            continue
        target = destination / source.relative_to(template_root)
        if target.exists():
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, target)
        created.append(target)
    return created


# --- Crash-safe writes ------------------------------------------------------


def write_text_atomic(path: Path, text: str) -> None:
    """Write text via a temp file plus `os.replace`, so readers never see a partial file.

    Referat's guiding rule is that a crash must never lose captured audio or
    corrupt what describes it, so every write of a file the user or Claude Code
    will read goes through here rather than truncating the target in place. It
    also makes `referat rerun` safe: a failed re-transcription leaves the
    previous `transcript.md` intact rather than a truncated one.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(dir=str(path.parent), prefix=path.name, suffix=".tmp")
    tmp = Path(tmp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp, path)
    except BaseException:
        tmp.unlink(missing_ok=True)
        raise


def write_json_atomic(path: Path, payload: dict[str, object]) -> None:
    """Write JSON through :func:`write_text_atomic`."""
    write_text_atomic(path, json.dumps(payload, indent=2, ensure_ascii=False) + "\n")
